'use client'
import Link from 'next/link'

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-black">
      <div className="py-16 sm:py-12 lg:py-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          {/* Header */}
          <div className="flex items-center space-x-4 sm:space-x-6 mb-8 sm:mb-12 lg:mb-16">
            <Link href="/" className="text-gray-600 dark:text-gray-400 p-2 rounded-lg">
              <svg className="w-5 h-5 sm:w-6 sm:h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
              </svg>
            </Link>
            <h1 className="text-xl sm:text-2xl font-light text-black dark:text-white tracking-wide">Disclaimer</h1>
          </div>

          {/* Content */}
          <div className="prose prose-gray dark:prose-invert max-w-none">
            <div className="border border-gray-300 dark:border-gray-800 p-6 sm:p-8 lg:p-12 bg-white dark:bg-black">
              
              {/* Last Updated */}
              <div className="mb-8 pb-6 border-b border-gray-200 dark:border-gray-800">
                <p className="text-sm text-gray-500 dark:text-gray-400 font-light">
                  <strong>Last updated:</strong> September 2025
                </p>
              </div>

              {/* Important Notice */}
              <div className="mb-8 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 p-6">
                <div className="flex items-start space-x-3">
                  <div className="w-6 h-6 text-red-500 flex-shrink-0 mt-0.5">
                    <svg className="w-full h-full" fill="currentColor" viewBox="0 0 24 24">
                      <path d="M12,2C6.48,2 2,6.48 2,12C2,17.52 6.48,22 12,22C17.52,22 22,17.52 22,12C22,6.48 17.52,2 12,2M13,17H11V15H13V17M13,13H11V7H13V13Z" />
                    </svg>
                  </div>
                  <div>
                    <h3 className="text-red-800 dark:text-red-200 font-normal mb-2" style={{ marginTop: '0' }}>Important Legal Notice</h3>
                    <p className="text-red-700 dark:text-red-300 text-sm font-light">
                      Please read this disclaimer carefully before using TransactProof. By using our service, you acknowledge and agree to these terms.
                    </p>
                  </div>
                </div>
              </div>

              {/* Section 1 */}
              <section className="mb-8">
                <h2 className="text-lg font-light text-black dark:text-white mb-4 tracking-wide">No Financial or Legal Advice</h2>
                <div className="space-y-4 text-sm text-gray-700 dark:text-gray-300 font-light leading-relaxed">
                  <p>
                    TransactProof is a technical tool that generates receipts for blockchain transactions. We are not financial advisors, 
                    tax consultants, accountants, or legal representatives. Any receipts or documents generated by our service are for 
                    informational purposes only and should not be considered financial, legal, or tax advice.
                  </p>
                </div>
              </section>

              {/* Section 2 */}
              <section className="mb-8">
                <h2 className="text-lg font-light text-black dark:text-white mb-4 tracking-wide">User Responsibility</h2>
                <div className="space-y-4 text-sm text-gray-700 dark:text-gray-300 font-light leading-relaxed">
                  <p>You are solely responsible for:</p>
                  <ul className="space-y-3">
                    <li className="flex items-start">
                      <span className="w-1 h-1 bg-orange-400 rounded-full mt-2 mr-3 flex-shrink-0"></span>
                      <span>Ensuring that the use of our receipts complies with your local tax, accounting, and legal requirements.</span>
                    </li>
                    <li className="flex items-start">
                      <span className="w-1 h-1 bg-orange-400 rounded-full mt-2 mr-3 flex-shrink-0"></span>
                      <span>Reporting your income, expenses, and cryptocurrency transactions correctly.</span>
                    </li>
                    <li className="flex items-start">
                      <span className="w-1 h-1 bg-orange-400 rounded-full mt-2 mr-3 flex-shrink-0"></span>
                      <span>Consulting with qualified professionals for legal, accounting, or tax matters.</span>
                    </li>
                  </ul>
                </div>
              </section>

              {/* Section 3 */}
              <section className="mb-8">
                <h2 className="text-lg font-light text-black dark:text-white mb-4 tracking-wide">No Guarantee of Accuracy</h2>
                <div className="space-y-4 text-sm text-gray-700 dark:text-gray-300 font-light leading-relaxed">
                  <p>While we strive to provide accurate transaction data, we cannot guarantee:</p>
                  <ul className="space-y-3">
                    <li className="flex items-start">
                      <span className="w-1 h-1 bg-orange-400 rounded-full mt-2 mr-3 flex-shrink-0"></span>
                      <span>Accuracy of third-party blockchain data providers (e.g., RPC nodes, explorers, APIs).</span>
                    </li>
                    <li className="flex items-start">
                      <span className="w-1 h-1 bg-orange-400 rounded-full mt-2 mr-3 flex-shrink-0"></span>
                      <span>Accuracy of price feeds used for fiat conversions.</span>
                    </li>
                    <li className="flex items-start">
                      <span className="w-1 h-1 bg-orange-400 rounded-full mt-2 mr-3 flex-shrink-0"></span>
                      <span>Availability and uptime of the blockchain networks.</span>
                    </li>
                  </ul>
                  <div className="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 p-4 mt-4">
                    <p className="text-yellow-800 dark:text-yellow-200 text-sm font-normal">
                      Receipts may contain inaccuracies if blockchain data or price feeds are incomplete, delayed, or incorrect.
                    </p>
                  </div>
                </div>
              </section>

              {/* Section 4 */}
              <section className="mb-8">
                <h2 className="text-lg font-light text-black dark:text-white mb-4 tracking-wide">Blockchain Risks</h2>
                <div className="space-y-4 text-sm text-gray-700 dark:text-gray-300 font-light leading-relaxed">
                  <p>Using blockchain networks involves risks outside of our control, including but not limited to:</p>
                  <ul className="space-y-3">
                    <li className="flex items-start">
                      <span className="w-1 h-1 bg-orange-400 rounded-full mt-2 mr-3 flex-shrink-0"></span>
                      <span>Network delays or congestion.</span>
                    </li>
                    <li className="flex items-start">
                      <span className="w-1 h-1 bg-orange-400 rounded-full mt-2 mr-3 flex-shrink-0"></span>
                      <span>Smart contract bugs or exploits.</span>
                    </li>
                    <li className="flex items-start">
                      <span className="w-1 h-1 bg-orange-400 rounded-full mt-2 mr-3 flex-shrink-0"></span>
                      <span>Irreversible transactions and loss of funds due to user mistakes.</span>
                    </li>
                  </ul>
                  <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 p-4 mt-4">
                    <p className="text-red-800 dark:text-red-200 text-sm font-normal">
                      We are not liable for any financial loss resulting from your use of blockchain networks or our service.
                    </p>
                  </div>
                </div>
              </section>

              {/* Section 5 */}
              <section className="mb-8">
                <h2 className="text-lg font-light text-black dark:text-white mb-4 tracking-wide">Limitation of Liability</h2>
                <div className="space-y-4 text-sm text-gray-700 dark:text-gray-300 font-light leading-relaxed">
                  <p>By using TransactProof, you acknowledge and agree that:</p>
                  <ul className="space-y-3">
                    <li className="flex items-start">
                      <span className="w-1 h-1 bg-orange-400 rounded-full mt-2 mr-3 flex-shrink-0"></span>
                      <span>We do not guarantee that receipts generated will be accepted by tax authorities, regulators, or third parties.</span>
                    </li>
                    <li className="flex items-start">
                      <span className="w-1 h-1 bg-orange-400 rounded-full mt-2 mr-3 flex-shrink-0"></span>
                      <span>Our liability is strictly limited as described in the{' '}
                        <Link href="/terms" className="text-orange-400 hover:text-orange-300 underline transition-colors duration-300">
                          Terms of Service
                        </Link>.
                      </span>
                    </li>
                    <li className="flex items-start">
                      <span className="w-1 h-1 bg-orange-400 rounded-full mt-2 mr-3 flex-shrink-0"></span>
                      <span>You use our service at your own risk.</span>
                    </li>
                  </ul>
                </div>
              </section>

              {/* Section 6 */}
              <section className="mb-8">
                <h2 className="text-lg font-light text-black dark:text-white mb-4 tracking-wide">Third-Party Links and Services</h2>
                <div className="space-y-4 text-sm text-gray-700 dark:text-gray-300 font-light leading-relaxed">
                  <p>
                    Our platform may use or link to third-party APIs, wallets, or services. We are not responsible for the content, 
                    availability, or security of such third-party services.
                  </p>
                  
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-6">
                    <div className="bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-800 p-4 text-center">
                      <div className="w-8 h-8 text-blue-400 mx-auto mb-2">
                        <svg className="w-full h-full" fill="currentColor" viewBox="0 0 24 24">
                          <path d="M12,2A10,10 0 0,1 22,12A10,10 0 0,1 12,22A10,10 0 0,1 2,12A10,10 0 0,1 12,2M12,4A8,8 0 0,0 4,12A8,8 0 0,0 12,20A8,8 0 0,0 20,12A8,8 0 0,0 12,4Z" />
                        </svg>
                      </div>
                      <h3 className="text-xs font-normal text-black dark:text-white mb-1">Blockchain APIs</h3>
                      <p className="text-xs text-gray-500 dark:text-gray-400 font-light">RPC nodes, explorers</p>
                    </div>
                    
                    <div className="bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-800 p-4 text-center">
                      <div className="w-8 h-8 text-green-400 mx-auto mb-2">
                        <svg className="w-full h-full" fill="currentColor" viewBox="0 0 24 24">
                          <path d="M12,2A10,10 0 0,1 22,12A10,10 0 0,1 12,22A10,10 0 0,1 2,12A10,10 0 0,1 12,2M12,4A8,8 0 0,0 4,12A8,8 0 0,0 12,20A8,8 0 0,0 20,12A8,8 0 0,0 12,4Z" />
                        </svg>
                      </div>
                      <h3 className="text-xs font-normal text-black dark:text-white mb-1">Price Feeds</h3>
                      <p className="text-xs text-gray-500 dark:text-gray-400 font-light">Market data providers</p>
                    </div>
                    
                    <div className="bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-800 p-4 text-center">
                      <div className="w-8 h-8 text-purple-400 mx-auto mb-2">
                        <svg className="w-full h-full" fill="currentColor" viewBox="0 0 24 24">
                          <path d="M12,2A10,10 0 0,1 22,12A10,10 0 0,1 12,22A10,10 0 0,1 2,12A10,10 0 0,1 12,2M12,4A8,8 0 0,0 4,12A8,8 0 0,0 12,20A8,8 0 0,0 20,12A8,8 0 0,0 12,4Z" />
                        </svg>
                      </div>
                      <h3 className="text-xs font-normal text-black dark:text-white mb-1">Wallet Services</h3>
                      <p className="text-xs text-gray-500 dark:text-gray-400 font-light">MetaMask, WalletConnect</p>
                    </div>
                  </div>
                </div>
              </section>

              {/* Final Warning */}
              <div className="bg-orange-50 dark:bg-orange-900/20 border border-orange-200 dark:border-orange-800 p-6">
                <div className="flex items-start space-x-3">
                  <div className="w-6 h-6 text-orange-500 flex-shrink-0 mt-0.5">
                    <svg className="w-full h-full" fill="currentColor" viewBox="0 0 24 24">
                      <path d="M13,14H11V10H13M13,18H11V16H13M1,21H23L12,2L1,21Z" />
                    </svg>
                  </div>
                  <div>
                    <h3 className="text-orange-800 dark:text-orange-200 font-normal mb-2" style={{ marginTop: '0' }}>Use at Your Own Risk</h3>
                    <p className="text-orange-700 dark:text-orange-300 text-sm font-light">
                      TransactProof is provided as a convenience tool. Always verify information independently and consult 
                      with qualified professionals for important financial, legal, or tax decisions.
                    </p>
                  </div>
                </div>
              </div>

            </div>
          </div>

          {/* Back to Home */}
          <div className="mt-8 sm:mt-12 text-center">
            <Link href="/" className="inline-flex items-center justify-center px-8 py-3 font-light tracking-wide border border-orange-400 text-orange-400 rounded-lg">
              Back to Home
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}