; Nixpacks config for deploying the API without a Dockerfile on Railway
; Place in apps/api and set Root Directory in Railway to apps/api

[phases.setup]
nixPkgs = [
  "bash",
  "coreutils",
  "curl",
  "gnutar",
  "gzip",
  "nodejs_18",
  "chromium",
  "nss",
  "freetype",
  "harfbuzz",
  "fontconfig",
  "dejavu_fonts"
]

[variables]
PUPPETEER_SKIP_DOWNLOAD = "true"
NODE_ENV = "production"
PORT = "3001"

[phases.install]
cmds = [
  "npm ci",
  "npx prisma generate --schema=./apps/api/prisma/schema.prisma"
]

[phases.build]
cmds = [
  "npm --prefix apps/api run build"
]

[phases.start]
cmd = "export PUPPETEER_EXECUTABLE_PATH=\"$(which chromium)\" && node dist/main.js"
